[package]
name = "zmq-cli"
version = "0.1.0"
authors = ["Carlo Sana <carlo.sana@unicredit.eu>"]

[dependencies]
zmq = "0.8.2"
regex = "0.2"
protobuf = { version = "1.3", features = ["with-bytes"] }
clap = "2.31.2"